"""Paper trading tracker — follows live signals and tracks outcomes.

Downloads historical data to simulate what would have happened if we
traded the signals generated by the live monitor.

Usage:
    python -m src.live.paper_trader          # Run paper trading simulation
    python -m src.live.paper_trader --days 30  # Simulate last 30 days
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timedelta
from pathlib import Path

import pandas as pd
import yfinance as yf

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from src.core.types import Candle, Direction
from src.structure.context import ContextBuilder
from src.strategies.fvg_reversal import FVGReversalStrategy
from src.ai.scorer import RuleBasedScorer


class PaperTrader:
    """Simulate paper trading with live signals."""

    def __init__(self):
        self.strategy = FVGReversalStrategy()
        self.context_builder = ContextBuilder()
        self.ai_scorer = RuleBasedScorer()
        self.initial_balance = 10000.0
        self.risk_per_trade = 0.01  # 1%

    def run_simulation(self, days: int = 30) -> dict:
        """Run paper trading simulation for last N days."""
        print(f"\n[PAPER TRADING] Simulating last {days} days...")

        # Download data
        gold = yf.Ticker("GC=F")
        df = gold.history(period="6mo", interval="1d")

        if len(df) < days + 30:
            return {"error": "Insufficient data"}

        # Convert to candles
        candles = []
        for idx, row in df.iterrows():
            ts = idx.to_pydatetime().replace(tzinfo=None)
            candles.append(Candle(
                timestamp=ts,
                open=float(row["Open"]),
                high=float(row["High"]),
                low=float(row["Low"]),
                close=float(row["Close"]),
                volume=float(row.get("Volume", 0)),
            ))

        # Simulate trading
        equity = self.initial_balance
        peak_equity = equity
        max_drawdown = 0
        trades = []
        equity_curve = [{"date": candles[0].timestamp.isoformat(), "equity": equity}]

        # Start from lookback period
        start_idx = 30
        for i in range(start_idx, len(candles)):
            current_candle = candles[i]
            current_price = current_candle.close

            # Check if any open trade hit SL/TP
            for trade in trades[:]:
                if trade["status"] == "OPEN":
                    hit = False
                    exit_price = 0

                    if trade["direction"] == "BUY":
                        if current_candle.low <= trade["sl"]:
                            hit = True
                            exit_price = trade["sl"]
                        elif current_candle.high >= trade["tp"]:
                            hit = True
                            exit_price = trade["tp"]
                    else:
                        if current_candle.high >= trade["sl"]:
                            hit = True
                            exit_price = trade["sl"]
                        elif current_candle.low <= trade["tp"]:
                            hit = True
                            exit_price = trade["tp"]

                    if hit:
                        if trade["direction"] == "BUY":
                            pnl = (exit_price - trade["entry"]) * trade["volume"] * 100
                        else:
                            pnl = (trade["entry"] - exit_price) * trade["volume"] * 100

                        pnl -= 7.0 * trade["volume"]  # Commission
                        equity += pnl
                        trade["status"] = "CLOSED"
                        trade["exit_price"] = exit_price
                        trade["exit_time"] = current_candle.timestamp.isoformat()
                        trade["pnl"] = round(pnl, 2)
                        trade["outcome"] = "WIN" if pnl > 0 else "LOSS"

            # Look for new entries
            available = candles[max(0, i-30):i+1]
            if len(available) < 20:
                equity_curve.append({"date": current_candle.timestamp.isoformat(), "equity": equity})
                continue

            try:
                ctx = self.context_builder.build(
                    symbol="XAUUSD",
                    candles_by_tf={"M15": available, "H4": available, "H1": available},
                    primary_tf="M15",
                    htf="H4",
                )
            except Exception:
                equity_curve.append({"date": current_candle.timestamp.isoformat(), "equity": equity})
                continue

            candidate = self.strategy.analyze(
                context=ctx,
                current_candle=current_candle,
                current_price=current_price,
                spread=3.0,
                session="london",
            )

            if candidate and candidate.rr_ratio >= 2.0:
                ai_decision = self.ai_scorer.score(candidate, ctx, spread=3.0, session="london")

                if ai_decision.ai_score >= 70:
                    # Position sizing
                    risk_amount = equity * self.risk_per_trade
                    sl_distance = abs(candidate.entry_price - candidate.stop_loss)

                    if sl_distance > 0:
                        volume = risk_amount / (sl_distance * 100)
                        volume = max(0.01, round(volume, 2))

                        trade = {
                            "entry_time": current_candle.timestamp.isoformat(),
                            "direction": candidate.direction.value,
                            "entry": current_price,
                            "sl": candidate.stop_loss,
                            "tp": candidate.take_profit_1,
                            "volume": volume,
                            "risk_amount": risk_amount,
                            "status": "OPEN",
                            "ai_score": ai_decision.ai_score,
                            "confluences": candidate.confluences,
                        }
                        trades.append(trade)

            # Track drawdown
            if equity > peak_equity:
                peak_equity = equity
            dd = (peak_equity - equity) / peak_equity * 100
            if dd > max_drawdown:
                max_drawdown = dd

            equity_curve.append({"date": current_candle.timestamp.isoformat(), "equity": equity})

        # Close any remaining open trades at last price
        for trade in trades:
            if trade["status"] == "OPEN":
                last_price = candles[-1].close
                if trade["direction"] == "BUY":
                    pnl = (last_price - trade["entry"]) * trade["volume"] * 100
                else:
                    pnl = (trade["entry"] - last_price) * trade["volume"] * 100
                pnl -= 7.0 * trade["volume"]
                equity += pnl
                trade["status"] = "CLOSED"
                trade["exit_price"] = last_price
                trade["pnl"] = round(pnl, 2)
                trade["outcome"] = "WIN" if pnl > 0 else "LOSS"

        # Calculate metrics
        closed_trades = [t for t in trades if t["status"] == "CLOSED"]
        winners = [t for t in closed_trades if t["pnl"] > 0]
        losers = [t for t in closed_trades if t["pnl"] <= 0]

        total_trades = len(closed_trades)
        win_rate = len(winners) / total_trades * 100 if total_trades > 0 else 0
        total_pnl = sum(t["pnl"] for t in closed_trades)
        avg_win = sum(t["pnl"] for t in winners) / len(winners) if winners else 0
        avg_loss = abs(sum(t["pnl"] for t in losers) / len(losers)) if losers else 0
        profit_factor = sum(t["pnl"] for t in winners) / abs(sum(t["pnl"] for t in losers)) if losers else 0
        expectancy = (win_rate/100 * avg_win) - ((1 - win_rate/100) * avg_loss)

        return {
            "period_days": days,
            "total_trades": total_trades,
            "winners": len(winners),
            "losers": len(losers),
            "win_rate": round(win_rate, 1),
            "total_pnl": round(total_pnl, 2),
            "avg_win": round(avg_win, 2),
            "avg_loss": round(avg_loss, 2),
            "profit_factor": round(profit_factor, 2),
            "expectancy": round(expectancy, 2),
            "max_drawdown": round(max_drawdown, 1),
            "final_equity": round(equity, 2),
            "return_pct": round((equity - self.initial_balance) / self.initial_balance * 100, 1),
            "trades": closed_trades,
            "equity_curve": equity_curve,
        }


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Paper trading simulation")
    parser.add_argument("--days", type=int, default=30, help="Days to simulate")
    args = parser.parse_args()

    trader = PaperTrader()
    result = trader.run_simulation(days=args.days)

    if "error" in result:
        print(f"[ERROR] {result['error']}")
        return

    print(f"\n{'='*60}")
    print(f"[RESULTS] Paper Trading Simulation ({result['period_days']} days)")
    print(f"{'='*60}")
    print(f"  Total Trades: {result['total_trades']}")
    print(f"  Win Rate: {result['win_rate']}%")
    print(f"  Total P&L: ${result['total_pnl']:,.2f}")
    print(f"  Return: {result['return_pct']}%")
    print(f"  Profit Factor: {result['profit_factor']}")
    print(f"  Expectancy: ${result['expectancy']:,.2f}")
    print(f"  Max Drawdown: {result['max_drawdown']}%")
    print(f"  Final Equity: ${result['final_equity']:,.2f}")

    if result["trades"]:
        print(f"\n  [TRADE LOG]")
        for t in result["trades"][-10:]:
            emoji = "WIN" if t["outcome"] == "WIN" else "LOSS"
            print(f"  [{emoji}] {t['direction']} @ {t['entry']:.2f} -> {t.get('exit_price', 'OPEN'):.2f} | P&L: ${t['pnl']:,.2f}")


if __name__ == "__main__":
    main()
