"""Common gateway contract for venue-agnostic market and execution code."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from src.core.types import AccountInfo, Candle, Deal, OrderRequest, OrderResult, Position, Tick


class VenueGateway(Protocol):
    """The subset of a trading venue used by the platform pipeline."""

    @property
    def connected(self) -> bool: ...

    async def connect(self) -> bool: ...
    async def disconnect(self) -> None: ...
    async def reconnect(self) -> bool: ...
    async def get_ohlcv(
        self, symbol: str, timeframe: str, count: int = 500, start: datetime | None = None
    ) -> list[Candle]: ...
    async def get_current_price(self, symbol: str) -> Tick: ...
    async def get_symbol_info(self, symbol: str) -> dict: ...
    async def get_account_info(self) -> AccountInfo: ...
    async def send_order(self, request: OrderRequest) -> OrderResult: ...
    async def modify_position(
        self, ticket: int, sl: float | None = None, tp: float | None = None
    ) -> OrderResult: ...
    async def close_position(self, ticket: int) -> OrderResult: ...
    async def get_positions(self, symbol: str | None = None) -> list[Position]: ...
    async def get_position_deals(self, position_id: int) -> list[Deal]: ...
